### ISSUE TITLE
Take screenshots of components for documentation pages

### ISSUE THREAD

**Issue by woutermont** [digita-ai/ui-transfer#20]
┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=701480416) by [Unito](https://www.unito.io)

**Comment by BelgianNoise** [comment]
![image](https://user-images.githubusercontent.com/38424924/121142383-36ec9780-c83c-11eb-87eb-27340853ea3d.png)
![image](https://user-images.githubusercontent.com/38424924/121142480-4ec41b80-c83c-11eb-8b01-38a16194ec3c.png)
![image](https://user-images.githubusercontent.com/38424924/121142560-64394580-c83c-11eb-87bd-de7016e38222.png)
![image](https://user-images.githubusercontent.com/38424924/121142609-76b37f00-c83c-11eb-8c11-ece90a3e82c0.png)
![image](https://user-images.githubusercontent.com/38424924/121142665-86cb5e80-c83c-11eb-823c-fdf1a339ab79.png)
![image](https://user-images.githubusercontent.com/38424924/121142767-9f3b7900-c83c-11eb-895a-b18b7129d87b.png)
